"""init

Revision ID: c6a129950e58
Revises: 
Create Date: 2025-08-13 05:58:41.827599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6a129950e58'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_monitored', sa.Boolean(), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channels_username'), ['username'], unique=False)

    op.create_table('signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('message_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('side', sa.Enum('long', 'short', name='tradeside'), nullable=False),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('stop_loss', sa.JSON(), nullable=True),
    sa.Column('take_profits', sa.JSON(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('last_checked_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'message_id', name='uq_channel_message')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signals_channel_id'), ['channel_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_message_date'), ['message_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_message_id'), ['message_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_side'), ['side'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_symbol'), ['symbol'], unique=False)

    op.create_table('signal_editions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_editions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_editions_signal_id'), ['signal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_editions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_editions_signal_id'))

    op.drop_table('signal_editions')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_symbol'))
        batch_op.drop_index(batch_op.f('ix_signals_side'))
        batch_op.drop_index(batch_op.f('ix_signals_message_id'))
        batch_op.drop_index(batch_op.f('ix_signals_message_date'))
        batch_op.drop_index(batch_op.f('ix_signals_channel_id'))

    op.drop_table('signals')
    with op.batch_alter_table('channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channels_username'))

    op.drop_table('channels')
    # ### end Alembic commands ###
